Controllers/MessageBoardController.cs
using System;
using System.Web;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
// Allows us to reference this class to instantiate instances of models:
using MessageBoard.Models;
// Necessary for using session:
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
// Necessary for password hashing:
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
// Necessary for connecting to our dbContext -> then to our database:
using MessageBoard.Data;

namespace MessageBoard.Controllers
{
    public class MessageBoardController : Controller
    {
        private MessageBoardContext _context;
        public MessageBoardController(MessageBoardContext context)
        {
            _context = context;
        }
        [HttpGet]
        public IActionResult Dashboard()
        {
            int? LoggedId = HttpContext.Session.GetInt32("UserId");
            if(LoggedId == null)
            {
                return RedirectToAction("Registration");
            }

            // User LoggedUser = _context.User.FirstOrDefault(u => u.UserId == (int)LoggedId);
            MessageBoardWrapper MBWrap = new MessageBoardWrapper()
            {
                AllMessages = _context.Messages
                    .Include(m => m.Creator)
                    .Include(children => children.ChildrenComments)
                    .ThenInclude(c => c.Creator)
                    .OrderByDescending(d => d.CreatedAt)
                    .ToList(),
            };
            return View("Dashboard", MBWrap);
        }

        [HttpPost]
        // lowercase "message" as parameter indicates the message obj from the form
        public IActionResult CreateMessage(MessageBoardWrapper message)
        {
            int? LoggedId = HttpContext.Session.GetInt32("UserId");
            if(LoggedId == null)
            {
                return RedirectToAction("Registration");
            }
            User LoggedUser = _context.User.FirstOrDefault(u => u.UserId == (int)LoggedId);
            message.Msg.UserId = LoggedUser.UserId;
            _context.Messages.Add(message.Msg);
            _context.SaveChanges();
            return RedirectToAction("Dashboard");
        }


        [HttpGet("delete/{MessageId}")]
        public RedirectToActionResult DeleteMessage(int MessageId)
        {
            int? LoggedId = HttpContext.Session.GetInt32("UserId");
            if(LoggedId == null)
            {
                return RedirectToAction("Registration");
            }
            Message ToDelete = _context.Messages.FirstOrDefault(m => m.MessageId == MessageId);

            if(ToDelete == null || ToDelete.UserId != (int)LoggedId)
            {
                return RedirectToAction("Dashboard");
            }
            _context.Remove(ToDelete);
            _context.SaveChanges();
            return RedirectToAction("Dashboard");
        }

        [HttpPost("messageboard/createcomment/{MessageId}")]

        public IActionResult CreateComment(MessageBoardWrapper comment, int MessageId)
        {
            int? LoggedId = HttpContext.Session.GetInt32("UserId");
            if(LoggedId == null)
            {
                return RedirectToAction("Registration");
            }
            User LoggedUser = _context.User.FirstOrDefault(u => u.UserId == (int)LoggedId);
            comment.Cmt.UserId = LoggedUser.UserId;
            comment.Cmt.MessageId = MessageId;
            _context.Comments.Add(comment.Cmt);
            _context.SaveChanges();
            return RedirectToAction("Dashboard");

            
        }
    }
}

Controllers/UserController.cs
using System;
using System.Web;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
// Allows us to reference this class to instantiate instances of models:
using MessageBoard.Models;
// Necessary for using session:
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
// Necessary for password hashing:
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;
// Necessary for connecting to our dbContext -> then to our database:
using MessageBoard.Data;

namespace MessageBoard.Controllers
{
    public class UserController : Controller
    {
        private MessageBoardContext _context;
        public UserController(MessageBoardContext context)
        {
            _context = context;
        }

        [HttpGet("")]
        public IActionResult Registration()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(LogRegWrapper user)
        {
            // Check to see if form data passes validations:
            if (ModelState.IsValid)
            {
                // Check to make sure email address is unique:
                if (_context.User.Any(u => u.Email == user.Register.Email))
                {
                    ModelState.AddModelError("Email", "Email in use. Already Registered? Please Log In.");
                    return View("Registration");
                }
                // If email is unique, process to hash password and create user in database:
                PasswordHasher<User> Hasher = new PasswordHasher<User>();
                user.Register.Password = Hasher.HashPassword(user.Register, user.Register.Password);
                _context.User.Add(user.Register);
                _context.SaveChanges();
                HttpContext.Session.SetInt32("UserId", user.Register.UserId);
                return RedirectToAction("Success");
            }
            else
            {
                return View("Registration");
            }
        }
        [HttpPost]
        public IActionResult Login(LogRegWrapper user)
        {
            if (ModelState.IsValid)
            {
                User userInDb = _context.User.FirstOrDefault(u => u.Email == user.Login.Email);
                if (userInDb == null)
                {
                    ModelState.AddModelError("Login.Email", "Invalid email/password.");
                    return View("Registration");
                }
                PasswordHasher<LogUser> Hasher = new PasswordHasher<LogUser>();
                PasswordVerificationResult Result = Hasher.VerifyHashedPassword(user.Login, userInDb.Password, user.Login.Password);

                if (Result == 0)
                {
                    ModelState.AddModelError("Login.Email", "Invalid email/password.");
                    return View("Registration");
                }
                HttpContext.Session.SetInt32("UserId", userInDb.UserId);
                return RedirectToAction("Success");
            }
            else 
            {
                return View("Registration");
            }
        }
        

        [HttpGet]
        public RedirectToActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Registration");
        }

        [HttpGet]
        public IActionResult Success()
        {
            // Note: C# provides language support for nullable types using a question mark as a suffix. For example, int?
            // Checking to see if a user is logged in session:
            int? LoggedId = HttpContext.Session.GetInt32("UserId");
            if(LoggedId == null)
            {
                return RedirectToAction("Registration");
            }
            User VBUser = _context.User.FirstOrDefault(u => u.UserId == (int)LoggedId);
            ViewBag.bananas = VBUser;

            MessageBoardWrapper MBWrap = new MessageBoardWrapper()
            {
                AllUsers = _context.User.ToList(),
                LoggedUser = _context.User.FirstOrDefault(u => u.UserId == (int)LoggedId),
            };

            return View("Success", MBWrap);
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MessageBoard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="MessageBoard" asp-action="Dashboard">MessageBoard</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 d-flex">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MessageBoard" asp-action="Dashboard">Dashboard</a>
                        </li>
                        <li class="nav-item ml-auto">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MessageBoard - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation/dist/additional-methods.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_RegisterLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MessageBoard</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="User" asp-action="Registration">MessageBoard</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 d-flex">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MessageBoard - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation/dist/additional-methods.js"></script>
    
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>